spring:
  data:
    web:
      pageable:
        default-page-size: 2
        max-page-size: 2000
        one-indexed-parameters: false
        page-parameter: page
        prefix: ''
        qualifier-delimiter: '_ '
        size-parameter: 'size '
      sort:
        sort-parameter: 'sort '
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
